# SPDX-License-Identifier: LicenseRef-P3-Plus
# SPDX-FileCopyrightText: Copyright (C) 2026 rootq <contact@rootq.de>
# === P3 PLUS – PROPRIETARY ===
# Licensed under LICENSE-PLUS (see repo root)
# Modification/Redistribution prohibited (see LICENSE-PLUS for security-patch exception)
# Contact: license@p3portal.org

# p3portal.org
"""PROJ-93: file-based CRUD for editor-managed Ansible playbook definitions.

Klon of ``packer_editor/service.py`` (Tech-Design § J), adapted to the Ansible
mount: the structured model lives in a Sidecar ``.p3editor.json`` inside
``ansible/<id>/``; the Sidecar's existence is the **marker** that a directory is
editor-managed. The editor lists/opens only marked directories and refuses to
overwrite/delete a foreign (ZIP/Git) directory that has no marker (AC-ROUND-1/2,
EC-4/5/6). The generated definition is a real ``ansible/<id>/`` directory
(``<id>.yml`` + ``meta.yaml`` + ``files/``) that the existing
``_load_all_metas()`` scan picks up automatically (AC-HOST-3).

Differences from packer_editor: ``ansible_dir`` instead of ``packer_dir``, no
``http/`` subdir, no password hashing, ``meta.yaml`` via the existing
``PlaybookMeta`` schema (parameters[] empty — MVP, AC-META-2).
"""
from __future__ import annotations

import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

import yaml
from pydantic import ValidationError

from backend.core.config import settings
from backend.models.playbooks import PlaybookMeta

from .schemas import AnsibleEditorModel, DefinitionSummary
from .transpile import transpile

_SIDECAR_NAME = ".p3editor.json"
_MARKER = "p3-ansible-editor"


class DefinitionExists(Exception):
    """Target id already exists as an editor-managed definition (use PUT)."""


class ForeignDefinition(Exception):
    """Target id exists but is NOT editor-managed (ZIP/Git) — never overwritten."""


class DefinitionNotFound(Exception):
    """No editor-managed definition with this id."""


def _ansible_dir() -> Path:
    return Path(settings.ansible_dir)


def _def_dir(definition_id: str) -> Path:
    return _ansible_dir() / definition_id


def _sidecar_path(definition_id: str) -> Path:
    return _def_dir(definition_id) / _SIDECAR_NAME


def is_editor_managed(definition_id: str) -> bool:
    return _sidecar_path(definition_id).is_file()


# ── Loading ───────────────────────────────────────────────────────────────────


def _load_sidecar(definition_id: str) -> AnsibleEditorModel | None:
    sidecar = _sidecar_path(definition_id)
    if not sidecar.is_file():
        return None
    try:
        raw = json.loads(sidecar.read_text())
        model = raw.get("model") if isinstance(raw, dict) and "model" in raw else raw
        return AnsibleEditorModel.model_validate(model)
    except (json.JSONDecodeError, ValidationError, OSError):
        return None


def _summary(model: AnsibleEditorModel) -> DefinitionSummary:
    return DefinitionSummary(
        id=model.id,
        name=model.name,
        description=model.description,
        required_role=model.required_role,
        targets=model.header.targets,
        task_count=len(model.tasks),
    )


def list_definitions() -> list[DefinitionSummary]:
    ansible_dir = _ansible_dir()
    if not ansible_dir.is_dir():
        return []
    out: list[DefinitionSummary] = []
    for entry in sorted(ansible_dir.iterdir()):
        if not entry.is_dir() or not (entry / _SIDECAR_NAME).is_file():
            continue
        model = _load_sidecar(entry.name)
        if model is None:
            continue
        out.append(_summary(model))
    return out


def get_definition(definition_id: str) -> AnsibleEditorModel | None:
    return _load_sidecar(definition_id)


# ── meta.yaml generation (Tech-Design § I) ────────────────────────────────────


def _build_meta_yaml(model: AnsibleEditorModel) -> str:
    """Generate a minimal, valid meta.yaml via the existing PlaybookMeta schema.

    parameters[] stays empty (MVP, AC-META-2). targets+become drive the run path
    (jobs.py dispatch); category lets it land in the right playbook tab.
    """
    meta = PlaybookMeta(
        name=model.name,
        description=model.description,
        playbook=f"{model.id}.yml",
        required_role=model.required_role,
        category=model.category,
        parameters=[],
        targets=model.header.targets,
        become=model.header.become,
    )
    body = yaml.safe_dump(meta.model_dump(exclude_none=True), sort_keys=False, allow_unicode=True)
    return "# p3portal.org (generated by P3 Ansible Visual Editor)\n" + body


def _sidecar_payload(model: AnsibleEditorModel) -> dict:
    return {
        "model": model.model_dump(),
        "_editor": {
            "marker": _MARKER,
            "schema_version": model.schema_version,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        },
    }


# ── Safe side-file writing ────────────────────────────────────────────────────


def _write_safe(root: Path, relpath: str, content: str) -> None:
    """Write content to root/relpath after verifying it stays inside root
    (defense-in-depth via commonpath, reuse of the _zip_safety hardening)."""
    root_resolved = str(root.resolve())
    target_norm = os.path.normpath(os.path.join(root_resolved, relpath))
    if os.path.commonpath([root_resolved, target_norm]) != root_resolved:
        raise ValueError(f"unsafe side-file path: {relpath!r}")
    target = Path(target_norm)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)


# ── Save / delete ─────────────────────────────────────────────────────────────


def save_definition(model: AnsibleEditorModel, *, is_update: bool) -> AnsibleEditorModel:
    """Persist the model + generate the definition directory.

    POST (is_update=False): existing **editor-managed** id → DefinitionExists
    (use PUT); existing **foreign** dir → ForeignDefinition (no overwrite, EC-4).
    PUT (is_update=True): the id must already be editor-managed (DefinitionNotFound).
    EC-12: previously-generated files/ + <id>.yml are cleared before re-writing so
    no-longer-referenced side-files are removed. Foreign dirs are never touched.
    """
    def_dir = _def_dir(model.id)
    exists = def_dir.is_dir()
    marker = is_editor_managed(model.id)

    if is_update:
        if not exists or not marker:
            raise DefinitionNotFound(model.id)
    else:
        if exists and marker:
            raise DefinitionExists(model.id)
        if exists and not marker:
            raise ForeignDefinition(model.id)

    yaml_text, files = transpile(model)
    meta_yaml = _build_meta_yaml(model)

    def_dir.mkdir(parents=True, exist_ok=True)
    # EC-12: clear generated content first (orphan side-file cleanup).
    shutil.rmtree(def_dir / "files", ignore_errors=True)
    for stale in def_dir.glob("*.yml"):
        stale.unlink()

    (def_dir / f"{model.id}.yml").write_text(yaml_text)
    (def_dir / "meta.yaml").write_text(meta_yaml)
    for relpath, content in files.items():
        _write_safe(def_dir, relpath, content)
    _sidecar_path(model.id).write_text(json.dumps(_sidecar_payload(model), indent=2) + "\n")

    return model


def build_preview(model: AnsibleEditorModel) -> tuple[str, dict[str, str], str]:
    """Generate the read-only projection without persisting (POST /preview).

    Returns the generated ``<id>.yml`` text + side-files + meta.yaml.
    """
    yaml_text, files = transpile(model)
    meta_yaml = _build_meta_yaml(model)
    return yaml_text, files, meta_yaml


def delete_definition(definition_id: str) -> bool:
    """Delete an editor-managed definition directory (EC-6).

    Returns False if it doesn't exist. Raises ForeignDefinition for a directory
    without the editor marker (never delete a ZIP/Git definition from here).
    """
    def_dir = _def_dir(definition_id)
    if not def_dir.is_dir():
        return False
    if not is_editor_managed(definition_id):
        raise ForeignDefinition(definition_id)
    shutil.rmtree(def_dir)
    return True
