# SPDX-License-Identifier: LicenseRef-P3-Plus
# SPDX-FileCopyrightText: Copyright (C) 2026 rootq <contact@rootq.de>
# === P3 PLUS – PROPRIETARY ===
# Licensed under LICENSE-PLUS (see repo root)
# Modification/Redistribution prohibited (see LICENSE-PLUS for security-patch exception)
# Contact: license@p3portal.org

# p3portal.org
"""PROJ-93: transpile the structured model → an Ansible playbook (Tech-Design § F/G).

A **pure function**: model → ``(yaml_text, files)``. The playbook is built as a
Python data structure and serialised with ``yaml.safe_dump`` (no string
templating) — so there is structurally no YAML/command injection (AC-VAL-2), and
Jinja values stay verbatim strings that Ansible renders itself (AC-JINJA-2).

One play, a linear task list (Non-Goal: block/rescue/multi-play). The ``hosts:``
line is derived from the target (§ G):
  * ``guest``     → ``managed``   (matches the PROJ-83 dynamic-inventory group)
  * ``localhost`` → ``localhost`` (Proxmox-REST style, implicit connection: local)

Task-level fields are emitted **only when set** (AC-LEVEL-2). ``register`` is
read from ``task.register_var`` (the model field is renamed to avoid shadowing
``BaseModel.register``; the YAML key stays ``register``).
"""
from __future__ import annotations

from typing import Any

import yaml

from .schemas import AnsibleEditorModel, AnsibleTask

_GEN_HEADER = "# p3portal.org (generated by P3 Ansible Visual Editor)\n"


def _hosts_for(targets: str) -> str:
    return "managed" if targets == "guest" else "localhost"


def _task_to_dict(task: AnsibleTask) -> dict[str, Any]:
    """One task → an ordered dict: name → <module sub-dict> → control fields."""
    td: dict[str, Any] = {}
    if task.name:
        td["name"] = task.name
    # The module FQCN is the task key; its value is the parameter sub-dict
    # (may be empty for parameter-less modules like ansible.builtin.ping).
    td[task.module] = dict(task.params)
    # Task-level fields, only when meaningfully set (AC-LEVEL-2).
    if task.when not in (None, ""):
        td["when"] = task.when
    if task.loop not in (None, "", []):
        td["loop"] = task.loop
    if task.register_var:
        td["register"] = task.register_var
    if task.become is not None:
        td["become"] = task.become
    if task.tags:
        td["tags"] = list(task.tags)
    if task.notify:
        # A single handler reads nicer as a string; multiple as a list (both valid).
        td["notify"] = task.notify[0] if len(task.notify) == 1 else list(task.notify)
    return td


def build_play(model: AnsibleEditorModel) -> list[dict[str, Any]]:
    """Build the playbook as a Python data structure (one play). Pure, testable."""
    h = model.header
    play: dict[str, Any] = {
        "name": model.name,
        "hosts": _hosts_for(h.targets),
        "gather_facts": h.gather_facts,
    }
    if h.become:
        play["become"] = True
    play["tasks"] = [_task_to_dict(t) for t in model.tasks]
    return [play]


def transpile(model: AnsibleEditorModel) -> tuple[str, dict[str, str]]:
    """Render the playbook to YAML text + collect side-files (files/<name>).

    Returns ``(yaml_text, files)`` where ``files`` maps relative paths under the
    definition directory to content. ``yaml.safe_dump`` keeps key order
    (sort_keys=False) and never line-wraps long Jinja strings (width large).
    """
    play_list = build_play(model)
    body = yaml.safe_dump(
        play_list,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=4096,
    )
    yaml_text = "---\n" + _GEN_HEADER + body
    files = {f"files/{name}": content for name, content in model.side_files.items()}
    return yaml_text, files
